"""PyFly Kernel — Foundation layer with zero external dependencies."""

from pyfly.kernel.exceptions import (
    AuthorizationException,
    BadGatewayException,
    BulkheadException,
    BusinessException,
    CircuitBreakerException,
    ConcurrencyException,
    ConflictException,
    DataIntegrityException,
    DegradedServiceException,
    ExternalServiceException,
    ForbiddenException,
    GatewayTimeoutException,
    GoneException,
    InfrastructureException,
    InvalidRequestException,
    LockedResourceException,
    MethodNotAllowedException,
    NotImplementedException,
    OperationTimeoutException,
    PayloadTooLargeException,
    PreconditionFailedException,
    PyFlyException,
    QuotaExceededException,
    RateLimitException,
    ResourceNotFoundException,
    RetryExhaustedException,
    SecurityException,
    ServiceUnavailableException,
    ThirdPartyServiceException,
    UnauthorizedException,
    UnsupportedMediaTypeException,
    ValidationException,
)
from pyfly.kernel.types import (
    ErrorCategory,
    ErrorResponse,
    ErrorSeverity,
    FieldError,
)

__all__ = [
    # Types
    "ErrorCategory",
    "ErrorSeverity",
    "FieldError",
    "ErrorResponse",
    # Base
    "PyFlyException",
    # Business
    "BusinessException",
    "ValidationException",
    "ResourceNotFoundException",
    "ConflictException",
    "PreconditionFailedException",
    "GoneException",
    "InvalidRequestException",
    "DataIntegrityException",
    "ConcurrencyException",
    "LockedResourceException",
    "MethodNotAllowedException",
    "UnsupportedMediaTypeException",
    "PayloadTooLargeException",
    # Security
    "SecurityException",
    "UnauthorizedException",
    "ForbiddenException",
    "AuthorizationException",
    # Infrastructure
    "InfrastructureException",
    "ServiceUnavailableException",
    "CircuitBreakerException",
    "RateLimitException",
    "BulkheadException",
    "OperationTimeoutException",
    "RetryExhaustedException",
    "DegradedServiceException",
    "NotImplementedException",
    # External Service
    "ExternalServiceException",
    "ThirdPartyServiceException",
    "BadGatewayException",
    "GatewayTimeoutException",
    "QuotaExceededException",
]
