pyfly:
  app:
    name: "pyfly-app"
    version: "0.1.0"
    description: ""
  profiles:
    active: ""
  banner:
    mode: "TEXT"
    location: ""
  logging:
    level:
      root: "INFO"
    format: "console"
  web:
    port: 8080
    host: "0.0.0.0"
    debug: false
    docs:
      enabled: true
    actuator:
      enabled: false
  data:
    enabled: false
    url: "sqlite+aiosqlite:///pyfly.db"
    echo: false
    pool-size: 5
  cache:
    enabled: false
    provider: "memory"
    ttl: 300
  messaging:
    provider: "memory"
  client:
    timeout: 30
    retry:
      max-attempts: 3
      base-delay: 1.0
    circuit-breaker:
      failure-threshold: 5
      recovery-timeout: 30
  admin:
    enabled: true
    path: "/admin"
    title: "PyFly Admin"
    theme: "auto"
    require-auth: false
    refresh-interval: 5000
  transactional:
    enabled: false
    saga:
      compensation_policy: STRICT_SEQUENTIAL
      default_timeout_ms: 300000
      max_concurrent_sagas: 100
      layer_concurrency: 0
      persistence_enabled: true
      metrics_enabled: true
      recovery_enabled: true
      recovery_interval_seconds: 60
      stale_threshold_seconds: 600
      cleanup_older_than_hours: 24
    tcc:
      default_timeout_ms: 30000
      retry_enabled: true
      max_retries: 3
      backoff_ms: 1000
      persistence_enabled: true
      metrics_enabled: true
    backpressure:
      strategy: adaptive
      concurrency: 10
      batch_size: 5
      failure_threshold: 50
      success_threshold: 2
      wait_duration_ms: 60000
